xcodeproj 'GW2Template'
inhibit_all_warnings!

def import_pods
    pod 'GW2Kit', :path => '../'
end

target :'GW2-iOS' do
    platform :ios, '7.0'
    import_pods
end

target :'GW2-OSX' do
    platform :osx, '10.9'
    import_pods
end
